version: 4.6.0.{build}

cache:
  - C:\Users\appveyor\.ant
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - '%APPVEYOR_BUILD_FOLDER%\Core\test\qa-functional\data'

image: Visual Studio 2019
platform: x64

environment:
  global:
    TSK_HOME: "C:\\sleuthkit"
    JDK_HOME: "C:\\Program Files\\Java\\jdk17"
    JAVA_HOME: "C:\\Program Files\\Java\\jdk17"
    PYTHON: "C:\\Python36-x64"

install:
  - ps: choco install nuget.commandline
  - ps: choco install ant --ignore-dependencies
  - ps: $env:Path="$($env:JAVA_HOME)\bin;$($env:Path);C:\ProgramData\chocolatey\lib\ant"
  - set PATH=C:\Python36-x64\';%PATH%
  - cd C:\
  - git clone https://github.com/sleuthkit/sleuthkit
  - cd %APPVEYOR_BUILD_FOLDER%
  - python setupSleuthkitBranch.py

services:
  - postgresql96

build_script:
  - cd %TSK_HOME%
  - nuget restore win32\libtsk -PackagesDirectory win32\packages
  - python win32\updateAndBuildAll.py -m
  - ps: pushd bindings/java
  - ps: ant -version
  - cmd: ant dist
  - ps: popd
  - ps: pushd case-uco/java
  - cmd: ant -q
  - ps: popd
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: ant -q build

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET NETBEANS_PLAT_VER=15
  - SET AUTOPSY_PLATFORM_PATH="%APPVEYOR_BUILD_FOLDER%/netbeans-plat/%NETBEANS_PLAT_VER%"
  - SET AUTOPSY_HARNESS_PATH="%AUTOPSY_PLATFORM_PATH%/harness"
  - cmd: ant -q ant -Dnbplatform.active.dir="%AUTOPSY_PLATFORM_PATH%" -Dnbplatform.default.harness.dir="%AUTOPSY_HARNESS_PATH%" test-no-regression
